version: '3'

networks:
  sit-development:
    name: 'sit-development'

services:

  server:
    container_name: node-app
    restart: always
    command: sh -c "npm run dev"
    build:
      context: ./server
      target: development
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./server/.env
    ports:
      - '3000:3000'
    networks:
      - sit-development
    depends_on:
      db:
        condition: service_healthy

  broker:
    container_name: broker-server
    image: 'eclipse-mosquitto:2'
    restart: always
    volumes:
      - ./mqtt/mosquitto:/mosquitto
    ports:
      - '38298:38298'
      - '9001:9001'
      - '1884:1883'
    networks:
      - sit-development

  db:
    container_name: sit-db
    image: 'postgres:13'
    environment:
      - POSTGRES_DB=sit-database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234567
    volumes:
      - 'data:/var/lib/postgresql/data'
    ports:
      - 5438:5432
    networks:
      - sit-development
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 1s
      timeout: 5s
      retries: 5


volumes:
  data:
    name: sit-dev-db
